apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "4500"
  MONGO_URI: "mongodb+srv://shanmukasagar:sagar%4005@cluster0.3bton.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
